name: flutter_base_getx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Multi language
  intl: ^0.19.0

  # Dio for network requests
  dio: ^5.8.0
  retrofit: ^4.4.2

  # Curl logger for Dio
  pretty_dio_logger: ^1.4.0
  curl_logger_dio_interceptor: ^1.0.0
  http_certificate_pinning: ^3.0.0

  # Logger
  logger: ^2.0.2+1

  # Http parser
  http_parser: ^4.1.2

  # Helpers for JSON models
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0

  # Functional programming
  dartz: ^0.10.1

  # Generate files
  flutter_gen: ^5.9.0

  # SVG support
  flutter_svg: ^2.0.6

  # GetX for state management
  get: ^4.7.2
  get_storage: ^2.1.1

  # ScreenUtil for responsive
  flutter_screenutil: ^5.9.3

  # Notifications
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  firebase_messaging_platform_interface: ^4.6.4

  # Device info
  device_info_plus: ^11.3.3
  android_id: ^0.4.0
  package_info_plus: ^8.3.0

  # Google Fonts
  google_fonts: ^6.2.1

  # Shimmer effect
  shimmer: ^3.0.0

  # Image caching
  flutter_blurhash: ^0.8.2
  cached_network_image: ^3.4.1

  # Sentry for error tracking
  sentry_flutter: ^8.13.2

  # Connectivity
  connectivity_plus: ^6.1.3

  # Splash screen
  flutter_native_splash: ^2.4.1

  # Jailbreak detection
  flutter_jailbreak_detection: ^1.10.0

  # Reactive streams
  rxdart: ^0.28.0
  collection: ^1.19.0

  # Dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Permission handling
  permission_handler: ^11.0.0

  # Path provider
  path_provider: ^2.0.11

  # UUID generation
  uuid: ^4.5.1

  # Encryption
  encrypt: ^5.0.1

  # Image picker
  image_picker: ^1.0.0

  # Throttling
  throttling: ^2.0.1

  # Universal platform
  universal_platform: ^1.1.0

  # Safe device
  safe_device: ^1.2.0

  dio_cache_interceptor: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  generate: true
  # Assets
  assets:
    - assets/images/
    - assets/icons/
#Flutter gen - image widget gen
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    image: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/gen

###
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/fe_logo_splash.png
  color_dark: "#ffffff"
  image_dark: assets/images/fe_logo_splash.png

  android_12:
    image: assets/images/fe_logo_android12splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/fe_logo_android12splash.png
    icon_background_color_dark: "#ffffff"

  web: false