// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJtXj70kIaL1Rb3gmWdNQ9wl-aBQRYMI',
    appId: '1:953318706997:web:c85114fd1972dbf79f867c',
    messagingSenderId: '953318706997',
    projectId: 'notification-c5f92',
    authDomain: 'notification-c5f92.firebaseapp.com',
    storageBucket: 'notification-c5f92.firebasestorage.app',
    measurementId: 'G-HTE47LNGSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPjkFFuqBRvcpqDRJMN1xttcXusBmFiE',
    appId: '1:953318706997:android:7223fe3ce236ccde9f867c',
    messagingSenderId: '953318706997',
    projectId: 'notification-c5f92',
    storageBucket: 'notification-c5f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJZwFbGOlWJKxzGXZTivC-YPqo9l1aB0U',
    appId: '1:953318706997:ios:3eed68c0b73d37ad9f867c',
    messagingSenderId: '953318706997',
    projectId: 'notification-c5f92',
    storageBucket: 'notification-c5f92.firebasestorage.app',
    iosBundleId: 'com.ahvuit.flutterBaseGetx',
  );
}
